server.port: @server.port@
management:
  security:
    flag: false
  metrics:
    export:
      statsd:
        flavor: etsy
        enabled: false
spring:
  application:
    name: @project.name@
  output:
    ansi:
      enabled: always
  cache:
    cache-names: resolveCountry
    caffeine:
      spec: maximumSize=500,expireAfterAccess=100s

kafka:
  bootstrap.servers: "localhost:29092"
  topic:
    global: global_topic
    result: result
    template: template
    reference: template_reference
  ssl:
    enable: false
    keystore-location: src/main/resources/cert/kenny-k.struzhkin.p12
    keystore-password: kenny
    key-password: kenny
    server-password: kenny12
    server-keystore-location: src/main/resources/cert/truststore.p12

clickhouse.db:
  url: "jdbc:clickhouse://localhost:8123/default"
  user: "user"
  password: "password"

geo.ip.service.url: "localhost:29092/v1/columbus"
wb.list.service.url: "localhost:29092/v1/wb_list"