server.port: @server.port@

kafka:
  bootstrap.servers: "localhost:29092"
  global.stream.topic: global_topic
  concrete.stream.topic: concrete
  result.stream.topic: result
  template.topic: template

clickhouse.db.url: "jdbc:clickhouse://localhost:8123/default"

geo.ip.service.url: "localhost:29092/v1/columbus"
wb.list.service.url: "localhost:29092/v1/wb_list"