server.port: @server.port@

spring:
  cache:
    cache-names: resolveCountry
    caffeine:
      spec: maximumSize=500,expireAfterAccess=100s

kafka:
  bootstrap.servers: "localhost:29092"
  global.stream.topic: global_topic
  concrete.stream.topic: concrete
  result.stream.topic: result
  topic.template: template
  topic.reference: template_reference

clickhouse.db.url: "jdbc:clickhouse://localhost:8123/default"

geo.ip.service.url: "localhost:29092/v1/columbus"
wb.list.service.url: "localhost:29092/v1/wb_list"